54321 learning git kyle
FranklinUniversityCompSciPracticum/GitActivities pull request #8
Opened 2020-09-09 02:15 UTC by seattlekyle

My submission for Activity 2

2020-09-09 03:34 UTC, franklinbrian requested changes

2020-09-09 03:34 UTC, franklinbrian commented on Activity1.md
> +This first activity will get you setup to complete the rest of the activities.ff
This change needs to be undone.  Please remove the ```ff``` from the line.

2020-09-16 04:24 UTC, franklinbrian approved these changes

2020-09-26 14:35 UTC, blgorman commented
Ordinarily, your pull requests would be accepted.  I am rejecting all pull requests because I need to keep the GitActivities repo clean for the future.  When working with your team, you would expect your PRs to be merged when they are correct and ready.

2020-09-26 14:35 UTC, closed without merging